enum MUTATION_TYPE {
  SAVE_PRODUCTS = "SAVE_PRODUCTS",
  SAVE_TOTAL_COST = "SAVE_TOTAL_COST",
  SAVE_TOTAL_ITEMS = "SAVE_TOTAL_ITEMS",
  SAVE_DISCOUNTS_APPLIED = "SAVE_DISCOUNTS_APPLIED",
  SAVE_TOTAL_COST_WITH_DISCOUNTS = "SAVE_TOTAL_COST_WITH_DISCOUNTS"
}

export default MUTATION_TYPE;
